apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: buildct
      image: archlinux:latest
      command: ["tail", "-f", "/dev/null"]
      securityContext:
        allowPrivilegeEscalation: true
      capabilities:
        add: ["SYS_ADMIN"]
      volumeMounts: 
        - mountPath: /var/run 
          name: docker-sock 
  volumes: 
    - name: docker-sock 
      hostPath: 
        path: /var/run 
