apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcooked-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-cooked-mysql
  template:
    metadata:
      labels:
        app: cloud-cooked-mysql
    spec:
      containers:
        - name: mysql
          image: 192.168.1.1:5000/mysql
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: cloudcooked-service-mysql
spec:
  type: ClusterIP
  selector:
    app: cloud-cooked-mysql
  ports:
    - name: sql
      port: 3306
      targetPort: 3306
