apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
      - name: flask
        image: 192.168.1.1:5000/flask
        ports:
        - containerPort: 5000
      - name: mysql
        image: 192.168.1.1:5000/mysql
        ports:
        - containerPort: 3306
