apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzapie-deployment
  labels:
    app: flask
spec:
  ports:
    - port: 80
      protocol: TCP
  replicas: 1
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
      - name: flask
        image: localhost:5000/flask
        ports:
        - containerPort: 5000
      containers:
      - name: mysql
        image: localhost:5000/mysql
        ports:
        - containerPort: 3306
