apiVersion: v1
kind: Service
metadata:
  name: cloudcooked-service
spec:
  ports:
    - name: flask_ext_port
      protocol: TCP
      port: 80
      targetPort: flask_app_port
  selector:
    app: flask

