version: "2"

services:
  flask:
    image: localhost:5000/flask
    build:
      context: .
      dockerfile: flaskct
  mysql:
    image: localhost:5000/mysql
    build:
      context: .
      dockerfile: mysql
